language: perl

dist: trusty

sudo: false
env:
  - "HARNESS_OPTIONS=j6"

install:
  - "cpanm -n Test::Pod Test::Pod::Coverage Mojolicious Net::CIDR::Lite Net::IP::Lite"
  - "cpanm -n --installdeps ."

perl:
  - "5.30"

matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
    - perl: 5.22
      env: COVERAGE=1
    - perl: 5.20
      env: COVERAGE=1
    - perl: 5.18
      env: COVERAGE=1
    - perl: 5.16
      env: COVERAGE=1
    - perl: 5.14
      env: COVERAGE=1
    - perl: 5.10
      env: COVERAGE=1
  allow_failures:
    - perl: blead

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

notifications:
  email: false
  irc:
    channels:
      - "irc.hackthissite.org#opensource"
    use_notice: true
    skip_join: true
