dist: trusty
sudo: false

language: perl

perl:
   - "5.26"

before_install:
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V

env:
   - "RELEASE_TESTING=1"
   - "AUTOMATED_TESTING=1"
   - "AUTHOR_TESTING=1"
   - "HARNESS_OPTIONS=j10:c"
   - "HARNESS_TIMER=1"

install:
   - cpanm --quiet --notest Devel::Cover::Report::Coveralls
   - cpanm --quiet --notest --installdeps .

script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
   - cover

after_success:
  - cover -report coveralls

matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
    - perl: 5.22
      env: COVERAGE=1
    - perl: 5.20
      env: COVERAGE=1
    - perl: 5.18
      env: COVERAGE=1
    - perl: 5.16
      env: COVERAGE=1
    - perl: 5.14
      env: COVERAGE=1
    - perl: 5.10
      env: COVERAGE=1
  allow_failures:
    - perl: blead

notifications:
  email: false
  irc:
    channels:
      - "irc.hackthissite.org#opensource"
    use_notice: true
    skip_join: true
